# Generated by Django 3.2.20 on 2023-08-02 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0003_auto_20230729_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age_range', models.CharField(max_length=10)),
                ('is_male', models.BooleanField(blank=True, default=None, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=100)),
                ('description_img', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=10)),
                ('background', models.TextField()),
                ('plot', models.TextField()),
                ('moral', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('characters', models.ManyToManyField(to='story.Character')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
        ),
    ]
