# Generated by Django 3.2.20 on 2023-08-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_remove_story_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='post',
        ),
    ]
