# Generated by Django 3.2.20 on 2023-08-02 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_remove_story_post'),
        ('board', '0003_auto_20230729_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.story'),
        ),
    ]
